universe=docker
docker_image=hanyingj/pymc3-sklearn

executable = unsupervised_trainingset.sh
transfer_input_files=/home/hjiang252/Normal/configurations/configurations_membership_dataset.csv, /home/hjiang252/Normal/dataset, /home/hjiang252/Normal/scripts/membership_with_true_parameter.py, /home/hjiang252/Normal/scripts/supervised_Normal.py, /home/hjiang252/Normal/scripts/unsupervised_Normal.py


# requesting resources
request_memory=3.5GB
request_cpus=1
request_disk=0.5GB

# parameters
environment="id=$(Step)"

# log files
error= /home/hjiang252/Normal/res/true3/unb$(Process).err
output= /home/hjiang252/Normal/res/true3/unb$(Process).out
log= /home/hjiang252/Normal/res/true3/unb$(Process).log
queue 81
