universe=docker
docker_image=hanyingj/pymc3-sklearn

executable=test.sh
transfer_input_files=/home/hjiang252/Normal/configurations/configurations_test.csv, /home/hjiang252/Normal/scripts/normal.py, /home/hjiang252/Normal/scripts/data_generator_Normal.py, /home/hjiang252/Normal/scripts/supervised_Normal.py, /home/hjiang252/Normal/scripts/unsupervised_Normal.py

# requesting resources
request_memory=5GB
request_cpus=1
request_disk=5GB

# parameters
environment="id=$(Step)"

# log files
error= /home/hjiang252/Normal/res/test/err$(Process).err
output= //home/hjiang252/Normal/res/test/out$(Process).out
log= /home/hjiang252/Normal/res/test/log$(Process).log
queue 2
