universe=docker
docker_image=hanyingj/pymc3-sklearn

executable = unsupervised.sh
transfer_input_files=/home/hjiang252/Normal/configurations/configurations_membership.csv, /home/hjiang252/Normal/dataset, /home/hjiang252/Normal/scripts/unsupervised_membership.py, /home/hjiang252/Normal/scripts/unsupervised_Normal.py


# requesting resources
request_memory=6.5GB
request_cpus=1
request_disk=0.5GB

# parameters
environment="id=$(Step)"

# log files
error= /home/hjiang252/Normal/res/membership/errun_unb$(Process).err
output= /home/hjiang252/Normal/res/membership/outun_unb$(Process).out
log= /home/hjiang252/Normal/res/membership/logun_unb$(Process).log
queue 297
